const INVOICE_CUSTOMER = "Facture_Client"
const COSTS = "Frais"
const ACCOUNTANT = "Document_Comptable"
const NUMERISATION_COSTS = 0
const NUMERISATION_INVOICES = 1
const NUMERISATION_ACCOUNTANT = 2

export {
  INVOICE_CUSTOMER,
  COSTS,
  NUMERISATION_COSTS,
  NUMERISATION_INVOICES,
  NUMERISATION_ACCOUNTANT,
  ACCOUNTANT,
}
